# PDFのビルドを行うworkflow
name: build

# masterブランチへのpush、またはvから始まるタグに対して実行
# 例えばv1.0.0など
on:
  push:
    branches:
      - master
    tags:
      - "v*"

env:
  # MakefileでDockerを使う機能を無効にする
  USE_DOCKER: no
  # ビルドされるファイルの名前。
  BUILT_FILE: [main, summary]

# 実行されるジョブの定義
jobs:
  # PDFのビルドジョブ
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: /workdir
        shell: bash
    container:
      # もし独自のDockerイメージを変更したい場合、ここを変更する
      image: ghcr.io/being24/latex-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move
        run: |
          shopt -s dotglob
          mv $GITHUB_WORKSPACE/* /workdir/
          shopt -u dotglob

      # 実際のビルドは `bin/build.sh` を実行している
      - name: Build
        run: ./bin/build.sh ${{ env.BUILT_FILE }}

      # 生成したPDFをGitHub Actionsにアップロードする
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          # アップロードするファイルを変更する場合、以下を変える
          path: /workdir/out/*.pdf

  # GitHubのReleaseを作成するジョブ
  # v1.0.0のようなタグがpushされた時のみ実行
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ビルドジョブでアップロードしたPDFをここでダウンロード
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pdf

      # Releaseを作成する
      # https://github.com/YOURNAME/YOURREPO/releases に 'Release タグ名' で作成
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.pdf
